import { subjectType } from "../interfaces/subjectType";

export const subjects: subjectType[] = [
  {
    id: 0,
    name: "DSA",
    folder: "АСД",
    fullName: "Data Structures and Algorithms",
    course: 1,
    semester: 1,
  },
  {
    id: 1,
    name: "BLCT",
    folder: "ДМКТ",
    fullName: "Business Language and Communication Technologies",
    course: 1,
    semester: 1,
  },
  {
    id: 2,
    name: "LAAG",
    folder: "Лінійна алгебра та аналітична геометрія",
    fullName: "Linear Algebra and Analytical Geometry",
    course: 1,
    semester: 1,
  },
  {
    id: 3,
    name: "DM",
    folder: "ДМ",
    fullName: "Discrete Mathematics",
    course: 1,
    semester: 2,
  },
  {
    id: 4,
    name: "SP",
    folder: "Соціологія Та Психологія",
    fullName: "Sociology and Psychology",
    course: 1,
    semester: 2,
  },
  {
    id: 5,
    name: "PTMS",
    folder: "ТІМС",
    fullName: "Probability Theory and Mathematical Statistics",
    course: 2,
    semester: 1,
  },
  {
    id: 6,
    name: "OOP",
    folder: "ООП",
    fullName: "Object-Oriented Programming",
    course: 2,
    semester: 2,
  },
  {
    id: 7,
    name: "AI",
    folder: "ОШІ",
    fullName: "The Basics of Artificial Intelligence",
    course: 2,
    semester: 2,
  },
  {
    id: 8,
    name: "D",
    folder: "DevOps",
    fullName: "DevOps",
    course: 3,
    semester: 1,
  },
  {
    id: 9,
    name: "CT",
    folder: "Критичне мислення",
    fullName: "Critical Thinking",
    course: 3,
    semester: 1,
  },
  {
    id: 10,
    name: "R",
    folder: "Роботехніка",
    fullName: "Robotics",
    course: 3,
    semester: 1,
  },
];
